#!/usr/bin/env python
#
# Driver file for SQL Worksheets based on SQLite
# (c) 2010 Rob Hague

from worksheet import *
import sqlite3, sys, optparse

class SqliteDB:
    """A Worksheet database object wrapping an SQLite 3 database"""
    def __init__(self, *args):
        if len(args) == 0:
            raise Exception("No DB filename supplied")
        self.filename = args[0]
        self.conn = sqlite3.connect(self.filename)
        
    def __del__(self):
        try:
            self.conn.close()
        except:
            pass

    def query(self, query):
        c = self.conn.cursor()
        result = {}
        try:
            r =  c.execute(query)
            result['headings'] = [item[0] for item in r.description]
            result['value'] = r.fetchall()
            result['status'] = "OK"
        except Exception:
            result['status'] = "error"
            result['value'] = "SQL error: "+str(sys.exc_info()[1])
        c.close()
        return result

    def title(self):
        return self.filename+" (SQLite)";

if __name__ == '__main__':
    start_worksheet_server(SqliteDB, sys.argv)
